name: pexels
version: 0.0.1
description: Unofficial Pexels REST Client for Dart
author: Kennedy Tochukwu Ekeoha <ekeohak@gmail.com>
repository: https://github.com/xenoken/pexels
homepage: https://github.com/xenoken/pexels
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test : ^1.0.0
